import './style.css';
import './portal.css';
import './admin.css';
import './admin-stats.css';
import './visual.css';

const categories = [
  ['all', '전체'], ['year', '신년운세'], ['month', '월간운세'], ['today', '오늘의 운세'],
  ['meeting', '만남'], ['crush', '짝사랑'], ['compatibility', '궁합'], ['worry', '연애고민'], ['saju', '사주 이야기']
];
const categoryName = Object.fromEntries(categories);
const seed = [
  { id: 1, category: 'today', title: '오늘, 마음의 속도를 조금 늦춰야 하는 이유', excerpt: '바쁜 하루 속에서도 당신에게 필요한 작은 신호를 발견해보세요.', date: '2026.08.20', read: 1284, tone: 'violet', body: '오늘은 서두르기보다 주변의 목소리에 귀 기울일수록 좋은 흐름이 열리는 날입니다.\n\n작은 선택 하나가 생각보다 긴 여운을 남길 수 있으니, 마음이 편안해지는 방향을 선택해보세요.' },
  { id: 2, category: 'meeting', title: '올해 하반기, 인연이 시작되는 세 가지 장면', excerpt: '우연처럼 찾아오는 만남에는 일정한 패턴이 있습니다.', date: '2026.08.18', read: 982, tone: 'peach', body: '새로운 인연은 거창한 사건보다 익숙한 일상에 살짝 모습을 드러냅니다.\n\n반복되는 장소, 자연스러운 대화, 그리고 호기심이 중요한 열쇠가 됩니다.' },
  { id: 3, category: 'month', title: '8월의 연애운: 관계를 다시 바라보는 시간', excerpt: '이번 달 당신의 관계에 필요한 것은 결론보다 이해입니다.', date: '2026.08.15', read: 764, tone: 'blue', body: '8월은 관계의 이름을 정하기보다 서로의 리듬을 확인하는 달입니다.\n\n조금 느린 대화가 오히려 더 깊은 진심을 전할 수 있습니다.' },
  { id: 4, category: 'compatibility', title: '잘 맞는 사람보다 오래 이해하는 사람', excerpt: '궁합은 완벽한 일치보다 다름을 다루는 방식에 가깝습니다.', date: '2026.08.12', read: 641, tone: 'gold', body: '서로 다른 두 사람이 편안함을 만드는 방식에는 배움이 필요합니다. 상대의 다름을 결점이 아닌 언어로 바라보세요.' },
  { id: 5, category: 'crush', title: '그 사람의 마음이 궁금한 날, 먼저 살펴볼 것', excerpt: '상대의 신호보다 내 마음의 방향을 먼저 읽어보세요.', date: '2026.08.09', read: 597, tone: 'rose', body: '좋아하는 마음은 때때로 상대의 행동을 크게 보이게 합니다. 오늘은 관찰과 기대를 잠시 나누어 바라보는 날입니다.' },
  { id: 6, category: 'saju', title: '사주를 처음 만나는 사람을 위한 안내서', excerpt: '태어난 순간의 기운을 삶의 언어로 읽는 방법.', date: '2026.08.05', read: 452, tone: 'green', body: '사주는 미래를 단정하는 도구가 아니라 자신을 이해하는 하나의 프레임입니다. 흐름을 알고 선택의 폭을 넓혀보세요.' }
];
let posts = JSON.parse(localStorage.getItem('yoonseul-posts') || 'null') || seed;
let state = { page: 'home', category: 'all', query: '', selected: null };

const app = document.querySelector('#app');
const save = () => localStorage.setItem('yoonseul-posts', JSON.stringify(posts));
const format = n => n.toLocaleString('ko-KR');
function nav(path, data = {}) { state = { ...state, page: path, ...data }; render(); window.scrollTo(0, 0); }
function card(p) { return `<article class="card" onclick="window.openPost(${p.id})"><div class="thumb ${p.tone}" ${p.image_url?`style="background-image:url('${p.image_url}');background-size:cover;background-position:center"`:''}><span>${categoryName[p.category]}</span>${p.image_url?'':'<b>✦</b>'}</div><div class="card-copy"><small>${p.date} · 조회 ${format(p.read)}</small><h3>${p.title}</h3><p>${p.excerpt}</p></div></article>`; }
function header() { return `<header><div class="nav-wrap"><a class="logo" href="#" onclick="window.go('home');return false"><i>Y</i><span>윤슬</span></a><nav>${categories.slice(1, 7).map(([k,v]) => `<a class="${state.category === k ? 'active':''}" href="#" onclick="window.go('category','${k}');return false">${v}</a>`).join('')}</nav><div class="actions"><button class="icon-btn" onclick="window.toggleSearch()">⌕</button><button class="menu-btn" onclick="window.go('admin')">관리자</button></div></div></header>`; }
function home() { const featured = posts.slice(0, 3); return `<main><section class="hero"><div class="hero-inner"><div><p class="eyebrow">A DAILY GUIDE TO YOUR DESTINY</p><h1>오늘의 흐름을<br/><em>읽어보세요.</em></h1><p class="hero-desc">흐릿한 마음에 작은 빛이 필요한 순간,<br/>윤슬이 당신의 다음 장면을 함께 바라봅니다.</p><button class="primary" onclick="window.go('category','today')">오늘의 운세 보기 <span>→</span></button></div><div class="orb"><div class="orb-inner">오늘의<br/><strong>빛</strong></div></div></div></section><section class="section intro"><div><p class="eyebrow">CURATED FOR YOU</p><h2>지금, 당신에게<br/><em>필요한 이야기</em></h2></div><p class="intro-text">운세는 정해진 답을 알려주는 것이 아니라<br/>내 안의 가능성을 발견하는 방법입니다.</p></section><section class="section"><div class="section-head"><div><p class="eyebrow">EDITOR'S PICK</p><h2>추천 콘텐츠</h2></div><a href="#" onclick="window.go('category','all');return false">전체 보기 <span>→</span></a></div><div class="grid featured">${featured.map(card).join('')}</div></section><section class="band"><div class="band-inner"><div><p class="eyebrow">NEED A LITTLE MORE CLARITY?</p><h2>혼자 고민하지 마세요.</h2><p>당신의 이야기를 들려주시면, 조금 더 깊이 함께 바라볼게요.</p></div><button class="light-btn" onclick="window.go('consult')">1:1 상담 안내 <span>→</span></button></div></section><section class="section"><div class="section-head"><div><p class="eyebrow">LATEST STORIES</p><h2>새로 올라온 이야기</h2></div><a href="#" onclick="window.go('category','all');return false">더 보기 <span>→</span></a></div><div class="grid">${posts.slice(3).map(card).join('')}</div></section></main>`; }
function listing() { const filtered = posts.filter(p => (state.category === 'all' || p.category === state.category) && [p.title,p.excerpt].join(' ').toLowerCase().includes(state.query.toLowerCase())); return `<main class="listing section"><div class="page-title"><p class="eyebrow">STORIES & INSIGHTS</p><h1>${categoryName[state.category]}</h1><p>당신의 오늘에 닿는 운세 이야기를 만나보세요.</p></div><div class="filters"><div class="chips">${categories.map(([k,v]) => `<button class="chip ${state.category===k?'selected':''}" onclick="window.go('category','${k}')">${v}</button>`).join('')}</div><div class="search"><input id="query" value="${state.query}" placeholder="콘텐츠 검색" onkeydown="if(event.key==='Enter')window.search(this.value)"/><button onclick="window.search(document.querySelector('#query').value)">⌕</button></div></div><div class="grid list-grid">${filtered.length ? filtered.map(card).join('') : '<div class="empty">검색 결과가 없습니다.</div>'}</div></main>`; }
function detail() { const p = posts.find(x=>x.id===state.selected); if (!p) return home(); const visual = p.image_url ? `<div class="detail-image ${p.tone}" style="background-image:url('${p.image_url}')"></div>` : `<div class="detail-image ${p.tone}">✦</div>`; return `<main class="detail section"><a class="back" href="#" onclick="window.go('category','${p.category}');return false">← ${categoryName[p.category]} 목록</a><div class="detail-head"><p class="eyebrow">${categoryName[p.category]} · ${p.date}</p><h1>${p.title}</h1><p>${p.excerpt}</p><small>조회 ${format(p.read)}</small></div>${visual}<div class="article-body">${p.body.split('\n').map(x=>x?`<p>${x}</p>`:'<br/>').join('')}</div></main>`; }
function consult() { return `<main class="consult section"><p class="eyebrow">PRIVATE READING</p><h1>당신의 이야기를<br/><em>천천히 들려주세요.</em></h1><p>현재 1:1 상담 서비스는 준비 중입니다. 상담이 시작되면 이 페이지를 통해 신청할 수 있습니다.</p><a class="primary inline" href="mailto:hello@yoonseul.example">상담 문의 남기기 <span>→</span></a></main>`; }
function adminStats() { const counts = posts.reduce((map, post) => { map[post.category] = (map[post.category] || 0) + 1; return map; }, {}); return `<div class="admin-stats"><div><b>${posts.length}</b><small>전체 게시글</small></div>${categories.slice(1, 5).map(([key, label]) => `<div><b>${counts[key] || 0}</b><small>${label}</small></div>`).join('')}</div>`; }
function admin() { return `<main class="admin section"><div class="page-title"><p class="eyebrow">CONTENT MANAGEMENT</p><h1>콘텐츠 관리</h1><p>D1 서버 저장을 사용하려면 관리자 토큰을 입력하세요. 토큰이 없으면 이 브라우저에서만 데모 저장됩니다.</p></div>${adminStats()}<input id="admin-token" class="token-input" type="password" placeholder="ADMIN_TOKEN (선택)" value="${sessionStorage.getItem('admin-token') || ''}" oninput="sessionStorage.setItem('admin-token',this.value)"/><form id="post-form" onsubmit="window.addPost(event)"><input name="title" required placeholder="게시글 제목"/><div class="form-row"><select name="category">${categories.slice(1).map(([k,v])=>`<option value="${k}" ${k==='today'?'selected':''}>${v}</option>`).join('')}</select><input name="date" type="date" value="2026-08-20"/></div><input name="excerpt" required placeholder="요약 문구"/><textarea name="body" required placeholder="본문 내용을 입력하세요"></textarea><label class="file-input">대표 이미지 <input name="image" type="file" accept="image/*"/></label><button class="primary" type="submit">게시글 등록 <span>→</span></button></form><div class="admin-list">${posts.map(p=>`<div class="admin-item"><div><b>${p.title}</b><small>${categoryName[p.category]} · ${p.date}</small></div><span><button onclick="window.editPost(${p.id})">수정</button><button onclick="window.removePost(${p.id})">삭제</button></span></div>`).join('')}</div></main>`; }
function referenceSections() { return `<section class="section portal-section"><div class="section-head"><div><p class="eyebrow">POPULAR FORTUNE</p><h2>인기 운세</h2></div><a href="#" onclick="window.go('category','all');return false">전체 보기 <span>→</span></a></div><div class="popular-grid">${posts.slice(0,4).map((p,i)=>`<button class="popular-item" onclick="window.openPost(${p.id})"><strong>${i+1}</strong><span><b>${p.title}</b><small>${categoryName[p.category]} · 조회 ${format(p.read)}</small></span></button>`).join('')}</div></section><section class="section portal-section free-panel"><div class="section-head"><div><p class="eyebrow">FREE SERVICES</p><h2>무료 운세</h2></div></div><div class="service-grid">${[['today','오늘의 운세','오늘 하루의 흐름을 확인해보세요.','☼'],['compatibility','신통방통 궁합','사랑과 관계의 방향을 살펴봅니다.','◌'],['saju','나의 사주 이야기','태어난 순간의 기운으로 나를 이해합니다.','✧'],['month','이번 달 운세','이번 달에 필요한 선택의 힌트입니다.','☾']].map(([k,t,d,icon])=>`<button class="service-card" onclick="window.go('category','${k}')"><span>${icon}</span><b>${t}</b><p>${d}</p><i>→</i></button>`).join('')}</div></section><section class="section portal-section"><div class="section-head"><div><p class="eyebrow">PRIVATE READERS</p><h2>전화 상담</h2></div><a href="#" onclick="window.go('consult');return false">상담 안내 <span>→</span></a></div><div class="reader-grid">${[['상록수','타로 · 인생 · 연애 · 금전','violet'],['수영','타로 · 연애 · 궁합 · 사주','peach'],['비타민','타로 · 연애 · 금전 · 인생','blue'],['안나','타로 · 인생 · 연애 · 사업','rose']].map(([n,t,tone])=>`<button class="reader-card" onclick="window.go('consult')"><span class="reader-avatar ${tone}">✦</span><b>${n}</b><small>${t}</small></button>`).join('')}</div></section>`; }
function render() { app.innerHTML = `${header()}${state.page==='home'?home()+referenceSections():state.page==='category'?listing():state.page==='detail'?detail():state.page==='consult'?consult():admin()}<footer><div class="footer-logo">윤슬</div><p>당신의 오늘에 닿는 작은 빛</p><small>© 2026 YOONSEUL. All rights reserved.</small></footer>`; }
window.go = (page, category) => nav(page, page==='category'?{category,query:''}:{});
window.openPost = id => { const p=posts.find(x=>x.id===id); p.read++; save(); nav('detail',{selected:id}); };
window.search = query => nav('category',{category:state.category,query});
window.toggleSearch = () => { const q=prompt('검색어를 입력하세요'); if(q!==null) window.search(q); };
window.addPost = async e => { e.preventDefault(); const f=new FormData(e.target); const token=sessionStorage.getItem('admin-token'); let image_url=null; if(token && f.get('image')?.size){ const upload=new FormData(); upload.append('file',f.get('image')); const media=await fetch('/api/media',{method:'POST',headers:{authorization:`Bearer ${token}`},body:upload}); if(!media.ok){ alert('이미지 업로드에 실패했습니다.'); return; } const uploaded=await media.json(); image_url=`/api/media?key=${encodeURIComponent(uploaded.key)}`; } if(token){ const response=await fetch('/api/posts',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({category_id:f.get('category'),title:f.get('title'),excerpt:f.get('excerpt'),body:f.get('body'),image_url,status:'published',published_at:f.get('date')})}); if(response.ok){ alert('D1에 게시글이 등록되었습니다.'); e.target.reset(); await hydrateFromDatabase(); return; } if(response.status===401){ alert('관리자 토큰이 올바르지 않습니다.'); return; } } posts.unshift({id:Date.now(),category:f.get('category'),title:f.get('title'),excerpt:f.get('excerpt'),date:f.get('date').replaceAll('-','.'),read:0,tone:'violet',body:f.get('body'),image_url}); save(); e.target.reset(); render(); alert('이 브라우저에 데모 게시글로 저장되었습니다.'); };
window.removePost = async id => { if(!confirm('이 게시글을 삭제할까요?')) return; const token=sessionStorage.getItem('admin-token'); if(token){ const response=await fetch(`/api/posts?id=${encodeURIComponent(id)}`,{method:'DELETE',headers:{authorization:`Bearer ${token}`}}); if(response.ok){ posts=posts.filter(p=>p.id!==id); render(); alert('D1에서 삭제되었습니다.'); return; } if(response.status===401){ alert('관리자 토큰이 올바르지 않습니다.'); return; } } posts=posts.filter(p=>p.id!==id); save(); render(); };
window.editPost = async id => { const p=posts.find(x=>x.id===id); if(!p) return; const title=prompt('제목',p.title); if(title===null) return; const category=prompt(`카테고리 코드와 이름\n${categories.slice(1).map(([k,v])=>`${k} = ${v}`).join('\n')}`,p.category); if(category===null) return; const excerpt=prompt('요약',p.excerpt); if(excerpt===null) return; const body=prompt('본문',p.body); if(body===null) return; const token=sessionStorage.getItem('admin-token'); if(token){ const response=await fetch(`/api/posts?id=${encodeURIComponent(id)}`,{method:'PUT',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({category_id:category,title,excerpt,body})}); if(response.ok){ alert('D1에서 수정되었습니다.'); await hydrateFromDatabase(); return; } if(response.status===401){ alert('관리자 토큰이 올바르지 않습니다.'); return; } } Object.assign(p,{category,title,excerpt,body}); save(); render(); alert('이 브라우저에서 수정되었습니다.'); };
render();
async function hydrateFromDatabase() {
  try {
    const response = await fetch('/api/posts');
    if (!response.ok) return;
    const remote = await response.json();
    if (!Array.isArray(remote) || remote.length === 0) return;
    posts = remote.map((p, index) => ({
      id: p.id,
      category: p.category_id,
      title: p.title,
      excerpt: p.excerpt || '',
      date: (p.published_at || p.created_at || '').slice(0, 10).replaceAll('-', '.'),
      read: p.views || 0,
      tone: ['violet', 'peach', 'blue', 'gold', 'rose', 'green'][index % 6],
      body: p.body || '', image_url: p.image_url ? `/api/media?key=${encodeURIComponent(p.image_url)}` : null
    }));
    render();
  } catch (error) {
    console.info('D1 is unavailable; showing local sample content.', error);
  }
}
hydrateFromDatabase();
